"""Export services — generate awesome lists, Obsidian vaults, etc."""

from starz.db.client import get_db


def generate_awesome_list() -> str:
    """Generate a curated awesome-list markdown from starred repos."""
    with get_db() as conn:
        rows = conn.execute(
            "SELECT full_name, description, language, category, summary, "
            "stargazers_count, html_url, health_score, homepage "
            "FROM repos ORDER BY category, stargazers_count DESC"
        ).fetchall()

    categories: dict[str, list] = {}
    total_stars = 0
    for r in rows:
        cat = r["category"] or "Other"
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(r)
        total_stars += r["stargazers_count"] or 0

    def fmt_stars(n: int) -> str:
        if n >= 1_000_000:
            return f"{n / 1_000_000:.1f}M"
        if n >= 1000:
            return f"{n / 1000:.1f}k"
        return str(n)

    lines = [
        "# My Starred Repos",
        "",
        f"A curated collection of **{len(rows)}** GitHub repositories across "
        f"**{len(categories)}** categories, totaling **{fmt_stars(total_stars)}** stars.",
        "",
        f"> Generated by [Starz](https://github.com/hamzaPixl/starz)",
        "",
        "## Contents",
        "",
    ]

    for cat in sorted(categories.keys()):
        anchor = cat.lower().replace("/", "").replace(" ", "-")
        lines.append(f"- [{cat}](#-{anchor}) ({len(categories[cat])})")

    lines.append("")

    for cat in sorted(categories.keys()):
        lines.append(f"## {cat}")
        lines.append("")

        # Table header
        lines.append("| Repository | Description | Stars |")
        lines.append("|:-----------|:------------|------:|")

        for r in categories[cat]:
            name = r["full_name"]
            url = r["html_url"]
            desc = r["description"] or r["summary"] or ""
            # Clean description for table
            desc = desc.replace("|", "/").replace("\n", " ").strip()
            if len(desc) > 100:
                desc = desc[:97] + "..."
            lang = f" `{r['language']}`" if r["language"] else ""
            stars = fmt_stars(r["stargazers_count"])

            lines.append(f"| [**{name}**]({url}){lang} | {desc} | {stars} |")

        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        f"*{len(rows)} repos, {len(categories)} categories, "
        f"{fmt_stars(total_stars)} total stars.*"
    )

    return "\n".join(lines)
